Remember to create database context. Y-Y
ERROR: cannot-open-database-test-requested-by-the-login-the-login-failed-login-fail ( at await _context.SaveChangesAsync();)

https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps
create database by nugget command line. Nuget Package Manager -> Packager Manage Console -> cd _dir (move to where u project location at ) -> enter command:
Add-Migration Initial
Update-Database